# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44784e6bac32e1fcab44b3d7dd9694f946dac202e248a287bad067d0dac415e86b84b5f683e9d69c572f71b7632361badca883c5faf67d6688c088cf3232567b

test:
  secret_key_base: ef8286e517544cbcd1a8c060527c509b2e64fdf0a6e2900e9075a62a46d39b4b24f9d81b42113b172c801930a8fcc511a2d4959b9647b89458b87ec68f84eaf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
